# Jordan - As Sabeel
# https://assabeel.net

# This code requires Selenium because the html is generated by javascript and so
# BS alone is unable to find <html> tags in the source because none have been generated

# This code uses BeautifulSoup to grab the title, article date, and article text from
# a single article

import requests
from bs4 import BeautifulSoup
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options


def grabPage(url):

    opts = Options()
    opts.set_headless()

    assert opts.set_headless
    browser = Firefox(options=opts)
    browser.get(url)

    page = browser.page_source
    soup = BeautifulSoup(page, 'lxml')

    title_box = soup.find('div', attrs={'class': 'NewsDetailsPage'}).find('h1')
    date_box = soup.find('span', attrs={'class': 'date'})
    article_box = soup.find('article')

    title = title_box.text.strip()
    date = date_box.text.strip()
    article = article_box.text.strip()

    return [title,date,article]

if __name__ == "__main__":

    page = 'http://alrai.com/article/10468767/'

    output = grabPage(page)
    for o in range (0,len(output)):
        print(output[o])