# Jordan - As Sabeel
# https://assabeel.net

# This code requires Selenium because the html is generated by javascript and so
# BS alone is unable to find <html> tags in the source because none have been generated

# This code uses BeautifulSoup to grab the title, article date, and article text from
# a single article

import requests
from bs4 import BeautifulSoup
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options

opts = Options()
opts.set_headless()

target_url = 'http://assabeel.net/news/2019/1/24/%D8%A7%D9%84%D8%A7%D8%AD%D8%AA%D9%84%D8%A7%D9%84-%D9%8A%D8%B3%D9%85%D8%AD-%D8%A8%D8%A7%D8%B3%D8%AA%D8%A6%D9%86%D8%A7%D9%81-%D8%A7%D8%AF%D8%AE%D8%A7%D9%84-%D8%A7%D9%84%D8%A7%D9%85%D9%88%D8%A7%D9%84-%D8%A7%D9%84%D9%82%D8%B7%D8%B1%D9%8A%D8%A9-%D9%84%D8%BA%D8%B2%D8%A9'

assert opts.set_headless
browser = Firefox(options=opts)
browser.get(target_url)

page = browser.page_source
soup = BeautifulSoup(page, 'lxml')

title_box = soup.find('div', attrs={'class': 'NewsDetailsPage'}).find('h1')
date_box = soup.find('span', attrs={'class': 'date'})
article_box = soup.find('article')

title = title_box.text.strip()
date = date_box.text.strip()
article = article_box.text.strip()

print(title)
print(date)
print(article)